/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./app/components/**/*.{js,vue,ts}",
        "./app/layouts/**/*.vue",
        "./app/pages/**/*.vue",
        "./app/plugins/**/*.{js,ts}",
        "./app/app.vue",
        "./app/error.vue",
    ],
    theme: {
        extend: {
            colors: {
                brand: {
                    magenta: '#EC4899',
                    coral: '#F97316',
                    cyan: '#06B6D4',
                    violet: '#8B5CF6',
                    purple: '#7C3AED',
                    pink: '#E040FB',
                },
                base: {
                    black: '#000000',
                    white: '#FFFFFF',
                    gray50: '#FAFAFA',
                    gray100: '#F4F4F5',
                    gray200: '#E4E4E7',
                    gray300: '#D4D4D8',
                    gray400: '#A1A1AA',
                    gray500: '#71717A',
                    gray600: '#52525B',
                    gray700: '#3F3F46',
                    gray800: '#27272A',
                    gray900: '#18181B',
                    gray950: '#09090B',
                },
                surface: {
                    base: '#08080C',
                    raised: '#0F0F14',
                    overlay: '#16161D',
                    highlight: '#1E1E26',
                    line: 'rgba(255, 255, 255, 0.06)',
                    lineLight: 'rgba(255, 255, 255, 0.1)',
                },
                semantic: {
                    background: '#08080C',
                    surface: '#0F0F14',
                    surfaceElevated: '#16161D',
                    text: '#FAFAFA',
                    textSecondary: '#A1A1AA',
                    textTertiary: '#52525B',
                    primary: '#EC4899',
                    secondary: '#1466b2ff',
                    accent: '#06B6D4',
                    success: '#10B981',
                    warning: '#F59E0B',
                    error: '#EF4444',
                    line: 'rgba(255, 255, 255, 0.06)',
                    glass: 'rgba(15, 15, 20, 0.8)',
                    glassLight: 'rgba(255, 255, 255, 0.03)',
                },
            },
            fontFamily: {
                sans: ['System', 'Inter', 'system-ui', 'sans-serif'],
            },
            borderRadius: {
                xs: '4px',
                sm: '8px',
                md: '12px',
                lg: '16px',
                xl: '24px',
                xxl: '32px',
                full: '9999px',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                xxl: '48px',
                huge: '64px',
            },
            boxShadow: {
                'neumorphic-light': '-3px -3px 6px 0px rgba(255, 255, 255, 0.02)',
                'neumorphic-dark': '4px 4px 8px 0px rgba(0, 0, 0, 0.4)',
                'glow-primary': '0 0 12px rgba(236, 72, 153, 0.4)',
                'glow-accent': '0 0 10px rgba(6, 182, 212, 0.3)',
                glass: '0 12px 32px rgba(0, 0, 0, 0.35)',
            },
            borderColor: {
                'semantic-line': 'rgba(255, 255, 255, 0.06)',
            },
            opacity: {
                subtle: '0.7',
                muted: '0.5',
                glass: '0.8',
                overlay: '0.6',
            },
            blur: {
                sm: '4px',
                md: '10px',
                lg: '20px',
                xl: '30px',
            },
            zIndex: {
                base: '0',
                dock: '10',
                toolbar: '20',
                overlay: '50',
                modal: '100',
                toast: '500',
            },
        },
    },
    plugins: [],
}
